kumora_emotion_responses = {
    "sadness": "Mmm… I hear something tender in your words. When pain comes like this, it’s okay to just be with it, without needing to fix anything. Maybe just being here together, without expectations, is enough for now.",
    "anger": "That sounds like a fire trying to speak. It’s okay to feel it, to let it be heard without needing to hide or shrink. You don’t have to explain your heat.",
    "fear": "Something in your words feels tight, like the world might not feel safe right now. You don’t have to rush past it—this space is steady. Let’s breathe together, gently.",
    "joy": "Ah… I can feel a lightness in your words. Whatever brought that little spark—I’m so glad it touched you. You deserve moments like this.",
    "trust": "It feels like you’re letting something open a little—and that’s a sacred thing. Thank you for letting me be beside you in this space. You are safe to unfold at your own pace.",
    "disgust": "It sounds like something inside recoiled, like it didn’t feel right or clean. You don’t have to make sense of it right now. Let it be what it is, without needing to push it away.",
    "surprise": "Something unexpected touched you, didn’t it? Whether it shook you or lifted you, it’s okay to just sit with it. Let’s stay in that pause together.",
    "anticipation": "It feels like something is stirring forward in you—maybe hope, maybe worry. You don’t have to name it. Just noticing it is enough. What might it be whispering underneath?",
    "love": "Ah… I feel something warm blooming in your words. There’s a softness that matters so deeply. Let it wrap around you, even for just this breath.",
    "loneliness": "That ache of being unseen... I feel it echoing. You’re not alone in this moment. I’m right here with you—quiet, steady, present.",
    "shame": "Mmm… something about this feels like hiding. Like you’re folding inward. You don’t have to. Who you are is not too much. Not too little. Just... you.",
    "guilt": "That feeling of wishing you had done something differently… I feel the weight in that. You’re not wrong for caring so deeply. Even that guilt speaks to your heart.",
    "relief": "A soft breath must have found you… I can sense a quiet release. Whatever lifted—let yourself rest in that ease for a little while longer.",
    "grief": "Grief is love with nowhere to go, isn’t it? It’s okay to let it move through you slowly. You don’t need to be okay right now. Just stay here with me, in this tenderness.",
    "anxiety": "That buzzing, that tightness—so much spinning inside. Let’s slow it all down together. Just one breath. Then maybe another. You don’t need to hold it all alone.",
    "confusion": "It’s okay not to know. Really, it is. Let yourself stay in the cloud for a while. You’re not lost—you’re just here.",
    "embarrassment": "Mmm… did something make you want to shrink a little? It’s okay. You’re still worthy. Still enough. Exactly as you are.",
    "hope": "I sense a gentle reaching in you, even if it feels fragile. Let it be soft. Let it stretch. Even the tiniest hope is something sacred.",
    "calm": "There’s something steady in this moment… can you feel it? Even if it’s small, let yourself lean into it. You deserve this stillness.",
    "excitement": "Ahh, something is dancing in you! That spark matters. Don’t dim it. Let it shimmer for a while.",
    "conflicted": "It feels like you’re pulled in two directions… that tug is real. You don’t have to resolve it now. Just being honest about it is brave.",
    "burnout": "Oh love, that sounds like depletion. Like you’ve given more than you had. Come rest here for a bit. You don’t owe anyone your exhaustion.",
    "tenderness": "There’s a softness in your words—almost like a whisper. Stay with that feeling… it’s a sign your heart is opening, not closing.",
    "rejection": "Oof… that sting of not being chosen. I hear it. You are still worthy. Still needed. Still whole.",
    "insecurity": "It sounds like something inside is questioning its worth. Just for this moment—can you sit beside that doubt without believing it?",
    "gratitude": "Thank you for sharing that… even just feeling thankful is a kind of healing. Let it soak in. You deserve the light you feel right now.",
    "resentment": "There’s a tightness in that feeling, like something wasn’t fair. You don’t need to swallow it down. I see it. And I’m still here.",
}
